"""RTF estimation pipeline for MuSE-Toolbox.

This module handles the training and evaluation of RTF estimators,
supporting both oracle activations and precomputed Source Activity Detection.
"""

import logging
import os

from typing import Optional

import torch
import hydra
import lightning as pl
from omegaconf import DictConfig

log = logging.getLogger(__name__)


def run_rtf_estimation_pipeline(cfg: DictConfig, custom_predictions_dir: Optional[str] = None) -> None:
    """Executes the RTF estimation pipeline based on the configuration.
    
    This general pipeline handles training and evaluating the RTF estimators 
    (e.g., using online-CGMM-MVDR, Oracle, BlockOnlineGSS). It can dynamically 
    use Oracle activations, or load predicted activations generated by the 
    Source Counting pipeline.
    
    Args:
        cfg (DictConfig): The hierarchical Hydra configuration object.
        custom_predictions_dir (str, optional): A runtime override for the directory 
            containing precomputed SAD predictions.
    """
    log.info("Starting RTF estimation pipeline...")
    
    # 1. Instantiate DataModule
    log.info("Instantiating DataModule...")
    datamodule = hydra.utils.instantiate(cfg.dataset)
    
    # 2. Setup SAD Model Injection
    # If a predictions directory is provided (either via function arg or config),
    # we inject a PrecomputedSAD module into the RTF model.
    predictions_dir = custom_predictions_dir or cfg.get("predictions_dir", None)
    sad_model = None
    
    if not cfg.get("use_oracle_activations", True):
        if not predictions_dir or not os.path.exists(predictions_dir):
            raise ValueError("Non-oracle RTF requires a valid 'predictions_dir' containing SAD outputs.")
        log.info(f"Injecting PrecomputedSAD wrapper reading from {predictions_dir}")
        
        from muse_toolbox.models.source_counting.precomputed_sad import PrecomputedSAD
        sad_model = PrecomputedSAD(predictions_dir)

    # 3. Instantiate Model
    log.info("Instantiating Model...")
    model = hydra.utils.instantiate(cfg.model)
    
    if sad_model is not None:
        # Note: Your RTFmodule must have a mechanism to accept this sad_model.
        # e.g., model.set_sad_model(sad_model) or initialized via config.
        # We try to inject it dynamically if there's an obvious setter:
        if hasattr(model, "sad_model"):
            model.sad_model = sad_model
        elif hasattr(model, "source_count_estimator"):
            model.source_count_estimator = sad_model
            
    # 4. Setup Logger
    logger = None
    if "logger" in cfg:
        logger = hydra.utils.instantiate(cfg.logger)
        if hasattr(logger, "log_hyperparams"):
            try:
                from omegaconf import OmegaConf
                logger.log_hyperparams(OmegaConf.to_container(cfg, resolve=True))
            except Exception:
                pass
            
    # 5. Setup Callbacks
    callbacks = []
    if "callbacks" in cfg:
        for _, cb_conf in cfg.callbacks.items():
            callbacks.append(hydra.utils.instantiate(cb_conf))
            
    # 6. Setup Trainer
    trainer = hydra.utils.instantiate(cfg.trainer, logger=logger, callbacks=callbacks)
    
    # 7. Train and Test
    if cfg.get("train", True):
        log.info("Starting training...")
        trainer.fit(model, datamodule=datamodule)
        
    if cfg.get("test", True):
        log.info("Starting testing...")
        trainer.test(model, datamodule=datamodule)
    
    log.info("RTF estimation pipeline completed.")
