"""RTF estimation pipeline for MuSE-Toolbox."""

import os
import torch
import hydra
import lightning as pl

class PrecomputedSAD(torch.nn.Module):
    """
    A wrapper module to load precomputed SAD (Source Activity Detection) 
    predictions from disk. This allows the RTF module to use cached 
    results instead of running the SAD model on the fly.
    """
    def __init__(self, predictions_dir):
        super().__init__()
        self.predictions_dir = predictions_dir

    def forward(self, x):
        # We expect x to be a HeterogeneousBatch or similar where .meta exists
        if not hasattr(x, "meta") or "scenario_id" not in x.meta:
            raise ValueError("Input batch lacks required 'meta' dictionary with 'scenario_id'.")
            
        scenario_ids = x.meta["scenario_id"]
        estimated_source_activities = []
        device = x.device if hasattr(x, "device") else torch.device("cpu")

        for sid in scenario_ids:
            filepath = os.path.join(self.predictions_dir, f"{sid}.pt")
            if not os.path.exists(filepath):
                raise FileNotFoundError(f"SAD prediction not found for {sid} at {filepath}")

            pred = torch.load(filepath, map_location=device)
            estimated_source_activities.append(pred)

        return estimated_source_activities


def run_rtf_estimation_pipeline(cfg, custom_predictions_dir=None) -> None:
    """Executes the RTF estimation pipeline based on the provided configuration.
    
    This general pipeline handles training and evaluating the RTF estimators 
    (e.g., using online-CGMM-MVDR, Oracle, BlockOnlineGSS). It can dynamically 
    use Oracle activations, or load predicted activations generated by the 
    Source Counting pipeline.
    
    Args:
        cfg: The configuration object (from Hydra).
        custom_predictions_dir (str, optional): A runtime override for the directory 
            containing precomputed SAD predictions.
    """
    print(f"Starting RTF estimation pipeline...")
    
    # 1. Instantiate DataModule
    print("Instantiating DataModule...")
    datamodule = hydra.utils.instantiate(cfg.dataset)
    
    # 2. Setup SAD Model Injection
    # If a predictions directory is provided (either via function arg or config),
    # we inject a PrecomputedSAD module into the RTF model.
    predictions_dir = custom_predictions_dir or cfg.get("predictions_dir", None)
    sad_model = None
    
    if not cfg.get("use_oracle_activations", True):
        if not predictions_dir or not os.path.exists(predictions_dir):
            raise ValueError("Non-oracle RTF requires a valid 'predictions_dir' containing SAD outputs.")
        print(f"Injecting PrecomputedSAD wrapper reading from {predictions_dir}")
        sad_model = PrecomputedSAD(predictions_dir)

    # 3. Instantiate Model
    print("Instantiating Model...")
    model = hydra.utils.instantiate(cfg.model)
    
    if sad_model is not None:
        # Note: Your RTFmodule must have a mechanism to accept this sad_model.
        # e.g., model.set_sad_model(sad_model) or initialized via config.
        # We try to inject it dynamically if there's an obvious setter:
        if hasattr(model, "sad_model"):
            model.sad_model = sad_model
        elif hasattr(model, "source_count_estimator"):
            model.source_count_estimator = sad_model
            
    # 4. Setup Logger
    logger = None
    if "logger" in cfg:
        logger = hydra.utils.instantiate(cfg.logger)
        if hasattr(logger, "log_hyperparams"):
            try:
                from omegaconf import OmegaConf
                logger.log_hyperparams(OmegaConf.to_container(cfg, resolve=True))
            except Exception:
                pass
            
    # 5. Setup Callbacks
    callbacks = []
    if "callbacks" in cfg:
        for _, cb_conf in cfg.callbacks.items():
            callbacks.append(hydra.utils.instantiate(cb_conf))
            
    # 6. Setup Trainer
    trainer = hydra.utils.instantiate(cfg.trainer, logger=logger, callbacks=callbacks)
    
    # 7. Train and Test
    if cfg.get("train", True):
        print("Starting training...")
        trainer.fit(model, datamodule=datamodule)
        
    if cfg.get("test", True):
        print("Starting testing...")
        trainer.test(model, datamodule=datamodule)
    
    print("RTF estimation pipeline completed.")
