_target_: muse_toolbox.models.components.feature_extractors.Condensed_LogMel_Feature_Extractor
_partial_: true
mode: "ref"
ref_channel: 0
n_mels: 80
f_min: 80
f_max: null
condense_method: "conv"
max_channels: 8
num_layers: 2
kernel_size: 3
dropout: 0.0
