_target_: muse_toolbox.models.components.feature_extractors.WGMSC_Feature_Extractor
_partial_: true
smoothing_time_constant: 0.5
whitening_time_constant: 0.5
smoothing_time_constant_rev: 0.5
whitening_time_constant_rev: 0.5
rev_features: true
wideband_features: false
