defaults:
  - feature_extractor: wgmsc
  - channel_combinator: null
  - source_count_estimator: transformer

_target_: muse_toolbox.models.source_counting.cosad.COSADmodule

# These will be resolved dynamically from other parts of the config tree
transform: ${transform}
batch_size: ${dataset.batch_size}


loss_config:
  CrossEntropy:
    weight: null

optimizer_config:
  AdamW:
    lr: 0.0001
    weight_decay: 0.01

lr_scheduler_config:
  ReduceLROnPlateau:
    monitor: "val/loss"
    mode: "min"
    factor: 0.5
    patience: 3
    threshold: 0.0001
    threshold_mode: "rel"
    cooldown: 0
    min_lr: 1e-07
    eps: 1e-08

metrics_train: {}
metrics_val:
  TolerantEventF1:
    tolerance_time: 0.5
  META2DF: {}
  MAE: {}
  MSE: {}
  Accuracy: {}
  ConfusionMatrix:
    max_sources: ${dataset.generation_config.max_sources}
    stage: "val"

metrics_test:
  TolerantEventF1:
    tolerance_time: 0.5
  META2DF: {}
  MAE: {}
  MSE: {}
  Accuracy: {}
  ConfusionMatrix:
    max_sources: ${dataset.generation_config.max_sources}
    stage: "test"

compute_complexity_metrics: False
check_causality: False
