# configs/dataset/base_simulated_dataset.yaml
# Tier 2 parameters specific to internally simulated/mixed datasets (e.g. BRUDEX, PRA_ANF).

defaults:
  - base_dataset

num_scenarios: [2400, 300, 300] # [4, 20, 10]
clean_speech_databases:
  Librispeech:
    class: LibrispeechDatabase

# The scenario mixing engine configuration
generation_config:
  _target_: muse_toolbox.data.ScenarioGenerationConfig
  max_sources: 4
  signal_lengths: 60.0
  initial_noise_only_duration:
    min: 0.5
    max: 5.0
  snrs: 
    min: 5.0
    max: 20.0
  source_power_range: 0.0
  time_between_events:
    min: 0.5
    max: 5.0
  activations_only: False
  remove_silence: True
  neglect_silence4oracle_sa: 0.4
  bridge_clean_speech_gaps: 0.1
  vad_threshold2define_oracle: -60
  vad_threshold2select_clean_speech: -30
  fix_seglen: False
