"""Utility functions and classes for MuSE-Toolbox."""

from muse_toolbox.utils.profiling_utils import LineTimer, CodeTimer, time_string, time_function, print_gpu_tensors
from muse_toolbox.utils.debug_utils import print_structure, deep_equal
from muse_toolbox.utils.format_utils import format_memory, format_flops, format_parameters
from muse_toolbox.utils.math import (
    db2amp, db2pow, amp2db, pow2db, rad2deg, deg2rad,
    hermitian_angle, complex_angle, subspace_angles, atan2, atan3, quadrant,
    covariance_SCM, growing_average_SCM, weighted_SCM, crossCovariance_SCM,
    covariance_Tyler, make2covariance_matrix, make2covariance_matrix_rel_lower_bound,
    spherical2cartesian, cartesian2spherical, slerp, successive_projections, moduloshift,
    cpu_gen_solve, effective_rank, is_hermitian, is_symmetric, is_positive_definite_h,
    is_positive_semi_definite_h, trace, makeHermitian, makeSymmetric,
    make_positive_definite_h, evd2matrix_h, makeMatrixUnitNorm, makeMatricesMaxUnitNorm,
    makeVectorUnitNorm, makeVectorUnitNorm_inPlace, peigvech, characteristic_subspace_h,
    characteristic_subspace, matrixsqrth, orthogonal_complement, vec2diagMat,
    parallel_projection, orthogonal_projection, oblique_projection, regularize,
    zero2identity, mytorch_eigvalsh, mytorch_eigh,
    randdir, randdir_orthogonal2vec, sample_complex_multivariate, gaussian, wmean,
    norm_by_sum, deviation,
    windowing, windowing_conv, exp_windowing, exp_windowing_conv,
    exp_windowing_recursive, exp_windowing_recursive_changing_factor,
    torchaudio_functional_fftconvolve_complex
)
from muse_toolbox.utils.tensor_ops import (
    check_all_elements_equal,
    dcn,
    to_one_hot,
    check_broadcastable,
    generalized_cat,
    get_real_dtype,
    inv_perm_indices,
    match_dims_to,
    nanappend,
    zeropad2fitdims,
)
from muse_toolbox.utils.system import (
    dac4torch_fun,
    move2device,
    memory,
    run_torch_function_with_settings,
)
from muse_toolbox.utils.dsp import (
    Beamformer, calc_beam_pattern,
    Frequency_Weighting, STFTtransform, slice2frames,
    calculate_t60, circularPositions, convolve_clean2microphone, convolve_white2microphone, rir2rtf, save_rirNoise2wav, simDiffuseNoise, simDiffuseNoiseANF, simRIR_shoebox, simRIR_shoebox_PRA,
    coherenceMatrix, gmsc, smoothCovarianceMatrix, smoothCovarianceMatrix_conv, wdo, windowedCovarianceMatrix,
    computeSNR, compute_power, compute_rms, normalize_components,
    covarianceSubtraction, covarianceWhitening, noise_subtraction, noise_whitening, noise_whitening_4_BOP, noise_whitening_noncholesky, noise_whitening_robust,
    gerkmannSPP_STFT, plot_vad_debug, vad_opt_fast_gen, vad_opt_original, vad_opt_slow,
    plot_coherence, plot_phaseogram, plot_spectrogram
)
from muse_toolbox.utils.audio_utils import load_audio
from muse_toolbox.utils.sample_parameter import sample_parameter

__all__ = [
    "amp2db",
    "atan2",
    "atan3",
    "Beamformer",
    "calc_beam_pattern",
    "calculate_t60",
    "cartesian2spherical",
    "characteristic_subspace",
    "characteristic_subspace_h",
    "check_all_elements_equal",
    "check_broadcastable",
    "circularPositions",
    "coherenceMatrix",
    "complex_angle",
    "compute_power",
    "compute_rms",
    "computeSNR",
    "convolve_clean2microphone",
    "convolve_white2microphone",
    "covariance_SCM",
    "covariance_Tyler",
    "covarianceSubtraction",
    "covarianceWhitening",
    "cpu_gen_solve",
    "crossCovariance_SCM",
    "dac4torch_fun",
    "db2amp",
    "db2pow",
    "deg2rad",
    "deviation",
    "effective_rank",
    "evd2matrix_h",
    "exp_windowing",
    "exp_windowing_conv",
    "exp_windowing_recursive",
    "exp_windowing_recursive_changing_factor",
    "Frequency_Weighting",
    "gaussian",
    "generalized_cat",
    "gerkmannSPP_STFT",
    "get_real_dtype",
    "gmsc",
    "growing_average_SCM",
    "hermitian_angle",
    "inv_perm_indices",
    "is_hermitian",
    "is_positive_definite_h",
    "is_positive_semi_definite_h",
    "is_symmetric",
    "load_audio",
    "make2covariance_matrix",
    "make2covariance_matrix_rel_lower_bound",
    "make_positive_definite_h",
    "makeHermitian",
    "makeMatricesMaxUnitNorm",
    "makeMatrixUnitNorm",
    "makeSymmetric",
    "makeVectorUnitNorm",
    "makeVectorUnitNorm_inPlace",
    "match_dims_to",
    "matrixsqrth",
    "memory",
    "moduloshift",
    "mytorch_eigh",
    "mytorch_eigvalsh",
    "nanappend",
    "noise_subtraction",
    "noise_whitening",
    "noise_whitening_4_BOP",
    "noise_whitening_noncholesky",
    "noise_whitening_robust",
    "norm_by_sum",
    "normalize_components",
    "oblique_projection",
    "orthogonal_complement",
    "orthogonal_projection",
    "parallel_projection",
    "peigvech",
    "plot_coherence",
    "plot_phaseogram",
    "plot_spectrogram",
    "plot_vad_debug",
    "pow2db",
    "quadrant",
    "rad2deg",
    "randdir",
    "randdir_orthogonal2vec",
    "regularize",
    "rir2rtf",
    "run_torch_function_with_settings",
    "sample_complex_multivariate",
    "sample_parameter",
    "save_rirNoise2wav",
    "simDiffuseNoise",
    "simDiffuseNoiseANF",
    "simRIR_shoebox",
    "simRIR_shoebox_PRA",
    "slerp",
    "slice2frames",
    "smoothCovarianceMatrix",
    "smoothCovarianceMatrix_conv",
    "spherical2cartesian",
    "STFTtransform",
    "subspace_angles",
    "successive_projections",
    "torchaudio_functional_fftconvolve_complex",
    "trace",
    "vad_opt_fast_gen",
    "vad_opt_original",
    "vad_opt_slow",
    "vec2diagMat",
    "wdo",
    "weighted_SCM",
    "windowedCovarianceMatrix",
    "windowing",
    "windowing_conv",
    "wmean",
    "zero2identity",
    "zeropad2fitdims",
    "move2device",
    "dcn",
    "to_one_hot",
    "plot_vad_debug",
    "format_parameters",
    "format_flops",
    "format_memory",
    "deep_equal",
    "print_structure",
    "print_gpu_tensors",
    "time_function",
    "time_string",
    "CodeTimer",
    "LineTimer",
]
