defaults:
  - dataset: brudex
  - model: cosad
  - transform: default
  - trainer: default
  - logger: wandb
  - callbacks: default
  - task: null
  - experiment: J3_brudex
  - _self_

# Global settings
task: source_counting
experiment_name: default_exp
train: True
test: True
predict: False
predictions_dir: null

paths:
  root_dir: ${oc.env:PROJECT_ROOT}
  output_dir: ${paths.root_dir}/outputs
  data_dir: ${paths.root_dir}/data
  log_dir: ${paths.output_dir}/logging

hydra:
  run:
    dir: ${paths.root_dir}/outputs/${task}/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${paths.root_dir}/outputs/${task}/${experiment_name}/multirun
    subdir: ${hydra.job.num}
  output_subdir: logging/.hydra
