defaults:
  - dataset: brudex_main
  - model: cosad
  - transform: default
  - trainer: default
  - logger: wandb
  - callbacks: default
  - task: null
  - _self_

# Global settings
task: source_counting
experiment_name: default_exp
train: True
test: True
predict: False
predictions_dir: "predictions/default_run"

paths:
  log_dir: "logs/"
  output_dir: "outputs/"
  data_dir: "data/"

hydra:
  run:
    dir: outputs/${task}/${experiment_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${task}/${experiment_name}/multirun
    subdir: ${hydra.job.num}
  output_subdir: logging/.hydra
